name: Build and Test

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: [ubuntu-latest, windows-latest]
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest]
    compiler: [g++, clang] # Добавьте список компиляторов, если необходимо

  steps:
  - uses: actions/checkout@v3
  - name: Set up ${{ matrix.os }}
   uses: actions/setup-${{ matrix.os }}@v3
   with:
    java-version: 'adopt-openjdk-11' # Добавить, если нужен Java
  - name: Install dependencies
   run: |
    if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
     sudo apt-get update
     sudo apt-get install -y cmake g++ clang # Установите зависимости для Linux
    elif [[ ${{ matrix.os }} == 'windows-latest' ]]; then
     choco install cmake # Установите зависимости для Windows
    fi
  - name: Configure CMake
   run: cmake . -DCMAKE_BUILD_TYPE=Release
  - name: Build
   run: cmake --build . --config Release
  - name: Run tests
   run: cmake --build . --target test --config Release
  - name: CPack
   run: cpack -G ZIP
  - name: Upload artifacts
   uses: actions/upload-artifact@v3
   with:
    name: CPack-artifacts-${{ matrix.os }}-${{ matrix.compiler }}
    path: pack/ProgLaba3-*
