name: 'C++ CI'

# Запускаем workflow при пуше в ветки lab1 или feature/github_actions
on: 
  # событие запускаем
  push:
    branches:
      - laba2
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: 3.14
          
      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          ctest --output-on-failure

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: 3.14

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          ctest --output-on-failure