name: 'C++ CI'

on: 
  push:
    branches:
      - laba5
      - feature/github_actions

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev cmake g++ make

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake..
          cmake --build.

      - name: Run tests
        run: |
         ./physics  # Replace with your executable name if different

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: ${{ github.event.release.name }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          DRAFT: false
          PRERELEASE: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:./build/physics  # Replace with your executable path
          asset_name: physics-linux  # Replace with your desired asset name
          asset_content_type: application/x-executable

      - name: Upload release asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:./build/physics  # Replace with your executable path
          asset_name: physics-linux.zip  # Replace with your desired asset name
          asset_content_type: application/zip
        run: |
          zip -j./build/physics-linux.zip./build/physics

  build_windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          choco install sfml
          choco install cmake
          choco install mingw

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake..
          cmake --build.

      - name: Run tests
        run: |
         .\physics.exe  # Replace with your executable name if different

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: ${{ github.event.release.name }}
          RELEASE_NOTES: ${{ github.event.release.body }}
          DRAFT: false
          PRERELEASE: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:./build/physics.exe  # Replace with your executable path
          asset_name: physics-windows.exe  # Replace with your desired asset name
          asset_content_type: application/x-msdownload

      - name: Upload release asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:./build/physics-windows.zip  # Replace with your zip file path
          asset_name: physics-windows.zip  # Replace with your desired asset name
          asset_content_type: application/zip
        run: |
          powershell Compress-Archive -Path./build/physics.exe -DestinationPath./build/physics-windows.zip -Force